# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "l/FrS1RuKPzBfr+qtgZA9nUib+27eR5NthTCTIaVZxA3y+lbp32VevN2xEqJ8a1xv8GY4b9d8S/AEka1RN3lUjo+kTpvDxFqxG8X1/NoRV1XYmRDoDF4YwN9KkI1jgTUm6Ib0WC8GnOlMJl2foFlB4I7RzveFYpyvcOtQaHJPOwCzk+pMTY+9K0e5vxZQNm6i8qJEuMsh2Re/DukAUKj3DnPsSz+1d782e7gBhidSVgI/absOsiCf3RkgDaxwKxaRCWL4fLxPaVuzfFo3USp+SsctD98QSPIgHq/KUOlX1N5rA5Dki/4WQ6jL3ZdCOOdoS6sFZcNmIpIlPEx+6Fh7357D7EzNZYMG8S3REc/IhhkxcAGeEnPJXqsijqhPabWb3r0+YaNcurqlOprm0i0gBWSJW5I9qsU43UUFNse/wefUUeSCn7WK5tCN1LzyR4DMwF9kJGe70pjiXcSNsrI7Dw6QCrb1Pg6LJNZ1QhEYCcnONn176eNUZWqhBeg2DduWabW9fT5YD3LF4SE0PydXNCQ/GbxXU9mz3KxJrbTQ5uW6SBYo7VKR00545QoJlVjc6LITp3gpXXyS1THSRfhfBt7a3PmdUD3WCWE5T4YKjM/13q4pL3i44XbfSFg7B2BCNeKUBC6PUpTIG/ZOrCLJSaxp+N/VIdVKBsuNPNv9K0="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
