travis:
  secure:
    BINSTAR_TOKEN: pm5lW6VCjcaJG925zachjazhJGT11gVwo6LKdwoYd8XylZUkELNkTgBqax6OnzTCo1MFk6JERa7p4gXFfr0Ww51oFUJQpTkQHyWq3qJ+yPl9RsHsNrKsuWRA5PR2HH4kPYd0/1m+WYSOuuRe4NvypeGxvgPpQls7Pw+zCEwXO39EvnA3fuzqZgGsIPB7AjQvM8Hwdi2HpwCrYxFzYBw6f9yEcnGxx13bqcl98Hv8UMzpQ3xXcXgn5iF1vHnKJ/qfuIg/d2Bp80G31HhPpZiz3Y1FKOO21U7SSL1AC4poTJip9K1ORyvATW9ovGnBi0E9WoAcRdr+OOaSXysOtxHSfltGR9Z2aIEfDeWNFSGB8coDiMgHQew91Owt3g6wX5BoJdvGKNzD7OXaCAdhcD6lQjUbqB8/uw3ZXRzqfcmCwPSOZq1eC//1Iv/pgo7FTDo0f0VmFbExQh61rXH80Jg/I0ZZVSXZPORP9f0bC0rJ14JxxyiecaNyUVcNWNOCy4xqDqNY3xW4rPo5BDFfyNZvZLVyzDzPQEBzF9UrfUCuMpoyHJ9C8CwhJ9Q4DbEZvxEpiFMjR/sXC+tcWqwN56TXEDjQp2aHhkD13wgsLoQXbK9QBRADInnacYD2sN0lNpJM3/T23JYHL0UvzljHtOZBPCu7U3bs4xZpvMuroR2vr3k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
