travis:
  secure:
    BINSTAR_TOKEN: l/FrS1RuKPzBfr+qtgZA9nUib+27eR5NthTCTIaVZxA3y+lbp32VevN2xEqJ8a1xv8GY4b9d8S/AEka1RN3lUjo+kTpvDxFqxG8X1/NoRV1XYmRDoDF4YwN9KkI1jgTUm6Ib0WC8GnOlMJl2foFlB4I7RzveFYpyvcOtQaHJPOwCzk+pMTY+9K0e5vxZQNm6i8qJEuMsh2Re/DukAUKj3DnPsSz+1d782e7gBhidSVgI/absOsiCf3RkgDaxwKxaRCWL4fLxPaVuzfFo3USp+SsctD98QSPIgHq/KUOlX1N5rA5Dki/4WQ6jL3ZdCOOdoS6sFZcNmIpIlPEx+6Fh7357D7EzNZYMG8S3REc/IhhkxcAGeEnPJXqsijqhPabWb3r0+YaNcurqlOprm0i0gBWSJW5I9qsU43UUFNse/wefUUeSCn7WK5tCN1LzyR4DMwF9kJGe70pjiXcSNsrI7Dw6QCrb1Pg6LJNZ1QhEYCcnONn176eNUZWqhBeg2DduWabW9fT5YD3LF4SE0PydXNCQ/GbxXU9mz3KxJrbTQ5uW6SBYo7VKR00545QoJlVjc6LITp3gpXXyS1THSRfhfBt7a3PmdUD3WCWE5T4YKjM/13q4pL3i44XbfSFg7B2BCNeKUBC6PUpTIG/ZOrCLJSaxp+N/VIdVKBsuNPNv9K0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
